---

- name: Add the user "{{ linux_user }}"
  ansible.builtin.user:
    name: "{{ linux_user }}"
    shell: /bin/bash
    groups: users, docker
    append: true

- name: Run the equivalent of "apt-get update" as a separate step
  ansible.builtin.apt:
    update_cache: true
    only_upgrade: true


- name: Install base aplications
  ansible.builtin.apt:
    pkg:
      - unzip
      - curl
      - ca-certificates
      - python3-pip
      - fail2ban
      - logrotate
    update_cache: true

- name: One way to avoid apt_key once it is removed from your distro
  block:
    - name: Docker |no apt key
      ansible.builtin.get_url:
        url: https://download.docker.com/linux/ubuntu/gpg
        dest: /etc/apt/keyrings/docker.asc
        mode: '644'

    - name: Add repository into sources list Docker
      ansible.builtin.apt_repository:
        repo: "deb [arch=amd64 signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable"
        state: present
        filename: docker
        mode: '644'

- name: Install docker
  ansible.builtin.apt:
    pkg:
      - docker
      - docker-ce
      - docker-ce-cli
      - docker-buildx-plugin
      - containerd.io
      - docker-compose-plugin
      - docker-compose
    update_cache: true
